FROM archlinux/archlinux:multilib-devel as BUILD

RUN sudo useradd -m build_user &&\
    sudo echo ' build_user ALL=(ALL)   NOPASSWD:ALL' >> /etc/sudoers
USER build_user
WORKDIR /home/build_user
RUN sudo pacman-key --init &&\
    sudo pacman -Syu --noconfirm&&\
    sudo pacman -S git cmake --noconfirm&&\
    git clone https://aur.archlinux.org/yay.git
WORKDIR /home/build_user/yay
RUN makepkg -si --noconfirm --syncdeps &&\
    yay -S conan mkcert --noconfirm

